GET http://localhost:3000/subject

###
POST http://localhost:3000/subject
Content-Type: application/json

{
    "name": "Computer Science",
    "teacher": "Mr. Informatics",
    "room": "131",
    "color": "#d7b1ec",
    "notes": "codeeeeeeeee",
    "type": "GK"
}

### 
PATCH http://localhost:3000/subject/6841d4982b92d985230b004d
Content-Type: application/json

{
    "notes": "changed notes to math"
}