GET http://localhost:3000/subject

###
POST http://localhost:3000/subject
Content-Type: application/json

{
    "name": "Maths",
    "teacher": "Mr. Maths",
    "room": "140",
    "color": "#d7b1ec",
    "notes": "new maths",
    "type": "LK"
}

### 
PATCH http://localhost:3000/subject/6841d4982b92d985230b004d
Content-Type: application/json

{
    "notes": "changed notes to math"
}

### 
DELETE  http://localhost:3000/subject/6841d4982b92d985230b004d
