GET http://localhost:3000/grade

###

GET http://localhost:3000/grade/6845da61c459203f47ec39ad

###
POST http://localhost:3000/grade
Content-Type: application/json

{
    "title": "Einstein Physicccc",
    "date": "2025-06-30",
    "subject": "6843e0094372b1b6172ad37a",
    "result": "",
    "notes": "einsteeeeein"
}

###
PATCH http://localhost:3000/grade/6845da61c459203f47ec39ad
Content-Type: application/json

{
    "title": "changed title"
}

###
DELETE http://localhost:3000/grade/6845da61c459203f47ec39ad