GET http://localhost:3000/subject

###
Get http://localhost:3000/subject/id/6843df34cfc1de52fa1ed2e6

###
Get http://localhost:3000/subject/type/LK

###
POST http://localhost:3000/subject
Content-Type: application/json

{
    "name": "Maths",
    "teacher": "Mr. Maths",
    "room": "140",
    "color": "#d7b1ec",
    "notes": "new maths",
    "type": "LK"
}

### 
PATCH http://localhost:3000/subject/6843e0704372b1b6172ad37f
Content-Type: application/json

{
    "color": "#9fd4c8"
}

### 
DELETE  http://localhost:3000/subject/6841d4982b92d985230b004d
